---
title: "626 mid1"
author: "yifei dai"
date: '2023-03-21'
output: html_document
---

```{r setup}
library(dplyr)
library(tidyverse)
library(tidytext)
library(rpart)
library(ipred)
library(e1071)
```


```{r}
# Read in data
dt <- read.table("data/training_data.txt", header = T)
test_data <- read.table("data/test_data.txt", header = T)
head(dt)
```
# task 1: binary classifier
```{r}
# dt$activity[!duplicated(dt$activity)]
# Data processing
dt_1 <- dt %>% 
  dplyr::select(-subject) %>%
  dplyr::mutate_at(dt$activity, as.numeric) %>%
  dplyr::mutate(bi_activity = ifelse(activity <= 3, 1, 0)) %>% # dynamic == 1, static & transition posture == 0
  dplyr::select(-activity)

test_data_1 <- test_data %>% 
  dplyr::select(-subject)
```

```{r}
set.seed(123)
train_id_1 <- sample(1:nrow(dt_1), 0.9*nrow(dt_1))
train_1 <- dt_1[train_id_1, ]
test_1 <- dt_1[-train_id_1, ]
y_tr <- test_1$bi_activity
test_1 %>% dplyr::select(-bi_activity)
train_1$b
```

```{r}
svm_linear <- svm(as.factor(bi_activity)~.,
                  data = train_1,
                  kernel = "linear", 
                  decision.values = TRUE)
svm_linear
y_pred <- predict(svm_linear, test_1)
cm <- table(y_tr, y_pred)
cm
roc_svm_line <- roc(y_tr, as.numeric(y_pred),
                  smooth = F,
                  levels = c(0,1),
                  direction='<')
plot(roc_svm_line , main ="ROC curve -- SVM with linear kernel")
```

```{r}
dr <- train_1 %>% dplyr::select(-bi_activity)

rm <- randomForest(x = dr,
                   y = train_1$bi_activity,
                   ntree = 500)

y_pred_rm <- predict(rm, test_1)
cm <- table(y_tr, y_pred_rm)
cm
roc_svm_line <- roc(y_tr, as.numeric(y_pred_rm),
                  smooth = F,
                  levels = c(0,1),
                  direction='<')
plot(roc_svm_line , main ="ROC curve -- randomforest")
```
```{r}
#model comparison
compare_matrix <- table(y_pred, y_pred_rm)
compare_matrix

```

```{r}
# prediction_1
y_pred_upload <- predict(svm_linear, test_data_1)
# write in
submit <- file("D:/1_ADesk/Learning/first winter semester/626/mid1/binary_2778.txt", "w" )
writeLines(as.character(y_pred_upload), submit)
close(submit)
```

```{r}
sessioninfo::session_info()
```
